feat: create gulp tasks
suprunivss/big-theater pull request #3
Opened 2021-07-14 19:18 UTC by suprunivss

2021-07-14 19:39 UTC, PahaTonk requested changes

2021-07-14 19:39 UTC, PahaTonk commented on .gitignore
> +/public
Добавь Enter

2021-07-14 19:39 UTC, PahaTonk commented on src/index.html
> +    <link rel="stylesheet" href="css/header.min.css" />
хедер выше

2021-07-14 19:39 UTC, PahaTonk commented on src/index.html
>                  alt="before"
alt человекочитаемым сделай

2021-07-14 19:39 UTC, PahaTonk commented on src/scss/footer.scss
> +;
лишняя точка с запятой

2021-07-14 19:39 UTC, PahaTonk commented on src/scss/panel.scss
> +.social {
Enter перед правилом

2021-07-14 19:39 UTC, PahaTonk commented on src/scss/theater.scss
> +.carousel {
+

2021-07-14 19:39 UTC, PahaTonk commented on src/scss/theater.scss
> +    &::before {
+

2021-07-14 19:39 UTC, PahaTonk commented on src/scss/preview.scss
> +  }
```$numbers: 1, 2, 3; 
@each $number in $numbers {
   &__item-#{$number} {
    background: url(../assets/img/-#{$number}.png) no-repeat;
  }
}
```

2021-07-14 19:39 UTC, PahaTonk commented on src/scss/preview.scss
> +    background: url(../assets/img/search.svg) no-repeat;
кавычки везде добавь/убрери

2021-07-15 11:03 UTC, suprunivss commented on .gitignore
> +/public
Исправил

2021-07-15 11:03 UTC, suprunivss commented on src/index.html
> +    <link rel="stylesheet" href="css/header.min.css" />
Исправил

2021-07-15 11:03 UTC, suprunivss commented on src/index.html
>                  alt="before"
Изменил

2021-07-15 11:03 UTC, suprunivss commented on src/scss/footer.scss
> +;
Убрал

2021-07-15 11:04 UTC, suprunivss commented on src/scss/panel.scss
> +.social {
+

2021-07-15 11:04 UTC, suprunivss commented on src/scss/theater.scss
> +    &::before {
+

2021-07-15 11:04 UTC, suprunivss commented on src/scss/preview.scss
> +  }
Сделал немного по другому

2021-07-15 11:04 UTC, suprunivss commented on src/scss/preview.scss
> +    background: url(../assets/img/search.svg) no-repeat;
Добивил

2021-07-15 11:22 UTC, PahaTonk requested changes

2021-07-15 11:22 UTC, PahaTonk commented on src/scss/main.scss
> +  @media (max-width: 1260px) {
Это не должно входить в фикс

2021-07-15 11:22 UTC, PahaTonk commented on src/scss/preview.scss
> +    &__item-#{$number} {
это тоже

2021-07-15 11:22 UTC, PahaTonk commented on src/scss/theater.scss
> +  @media (max-width: 992px) {
и это

2021-07-15 19:46 UTC, PahaTonk approved these changes
Approve

2021-07-15 19:47 UTC, merged